version: "3.7"
services:
  app:
    build:
      args:
        user: seun
        uid: 1000
      context: ./
      dockerfile: Dockerfile.dev
    image: nextdaysite-test
    restart: unless-stopped
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
    networks:
      - nextdaysite-test

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - nextdaysite-test
    
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - nextdaysite-test

networks:
  nextdaysite-test:
    driver: bridge
